### ISSUE TITLE
Geocode by locality

### ISSUE THREAD

**Issue by waldoj** [yoni/wetheentities#3]
For a given petition, geocode every locality that's mentioned (if any), rather than merely the countries. Then expose an endpoint to retrieve that information for a given petition. Ideally, provide a bulk download of petitions that have geocoded localities.

**Comment by yoni** [comment]
I think Open Calais is geocoding every locality already, but I'm only showing Country in the example. Are you not seeing cities etc.?

I like the idea of an endpoint that summarizes geographic data across many petitions.

**Comment by yoni** [comment]
@waldoj I'm sorry I didn't get to this on Saturday. I've confirmed that cities, regions, continents, and countries all work. Check out the [Open Calais entity index and definitions](http://www.opencalais.com/documentation/calais-web-service-api/api-metadata/entity-index-and-definitions) for a list of all the possible entity types. For a decent example, look at @heyitsgarrett's [wethevisualization](https://github.com/heyitsgarrett/wethevisualization/blob/master/js/site.js)

As I mentioned before, your point is regarding a separate end point for all geo data is well taken. Just wanted to make sure you're not blocked on that for the near term. :)

**Comment by waldoj** [comment]
Great—thank you, Yoni!

**Comment by yoni** [comment]
Closing this out. I opened #8 to track the bulk Geo API.
